added Welcome, Stale Bot
HarshCasper/SpeakEd pull request #41
Opened 2021-03-14 16:16 UTC by anjali1102

2021-03-15 12:14 UTC, HarshCasper requested changes

2021-03-15 12:14 UTC, HarshCasper commented on .github/workflows/greetings.yml
> +      - uses: anjali1102/Greeting-action@main
Do you really think it would work?

2021-03-15 12:14 UTC, HarshCasper commented on .github/workflows/greetings.yml
> +            <i> Check this <a href="https://docs.google.com/document/d/1WYYc2ymImxS6-TKB6pRX77A9zpXb_ujGjdpfMaTDXwc/edit">guide</a> before contributing.'
Don't copy-paste actions from other projects (In this case NeoAlgo) to other projects. It kills the open-source spirit.

2021-03-15 12:14 UTC, HarshCasper commented on .github/workflows/stale.yml
> +            from our [Telegram](https://t.me/tesseractcoding) or ping one of the
Tesseract Coding? Really?

2021-03-16 05:53 UTC, anjali1102 commented
Review pls

2021-03-16 12:54 UTC, HarshCasper requested changes
We would still need a `.github/stale.yml` with a content similar to this: 
```
# Number of days of inactivity before an issue becomes stale
daysUntilStale: 7
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 8
# Issues with these labels will never be considered stale
exemptLabels:
  - bug
  - do not merge yet
  - help wanted
  - high priority
  - pinned
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  Please reopen this issue once you commit the changes requested or
  make improvements on the code. Thank you for your contributions.
```

Example cited from NeoAlgo

2021-03-16 16:31 UTC, anjali1102 commented
> We would still need a `.github/stale.yml` with a content similar to this:
> 
> ```
> # Number of days of inactivity before an issue becomes stale
> daysUntilStale: 7
> # Number of days of inactivity before a stale issue is closed
> daysUntilClose: 8
> # Issues with these labels will never be considered stale
> exemptLabels:
>   - bug
>   - do not merge yet
>   - help wanted
>   - high priority
>   - pinned
> # Label to use when marking an issue as stale
> staleLabel: stale
> # Comment to post when marking an issue as stale. Set to `false` to disable
> markComment: >
>   This issue has been automatically marked as stale because it has not had
>   recent activity. It will be closed if no further activity occurs. Thank you
>   for your contributions.
> # Comment to post when closing a stale issue. Set to `false` to disable
> closeComment: >
>   Please reopen this issue once you commit the changes requested or
>   make improvements on the code. Thank you for your contributions.
> ```
> 
> Example cited from NeoAlgo

do I have to create new PR for this file or again do  ?

2021-03-17 17:25 UTC, closed without merging