Added Contributor
HarshCasper/SpeakEd pull request #43
Opened 2021-03-15 04:06 UTC by rohank2502

I have added the automatically updating contributor in read me !! 
Fixes #34

2021-03-15 12:15 UTC, HarshCasper requested changes

2021-03-15 12:15 UTC, HarshCasper commented on README.md
> +### Credit goes to these people:✨
Remove this

2021-03-15 12:15 UTC, HarshCasper commented on README.md
> +## Contributor
Make it `Contributors`

2021-03-15 12:15 UTC, HarshCasper commented on README.md
> +  <img src="https://contrib.rocks/image?repo=HarshCasper/SpeakEd" />
Indent this

2021-03-15 12:15 UTC, HarshCasper commented on README.md
> +
Remove this line

2021-03-17 03:43 UTC, rohank2502 commented on README.md
> +
Done suggested changes have a look !!

2021-03-22 11:56 UTC, HarshCasper approved these changes

2021-03-22 11:56 UTC, merged